import argparse

# parser = argparse.ArgumentParser()

def acm(parser):
    parser.add_argument('--model_name', type=str, default='SMHGC_acm', help='model_name')
    parser.add_argument('--path', type=str, default='./data/', help='The path of datasets')
    parser.add_argument('--order', type=int, default=2, help='aggregation orders')
    parser.add_argument('--weight_soft_h', type=float, default=0.5, help='weight_soft_h')
    parser.add_argument('--weight_soft_S', type=float, default=0.5, help='weight_soft_S')
    parser.add_argument('--K', type=int, default=300, help='discretize with k')
    parser.add_argument('--hidden_dim_x', type=int, default=128, help='hidden_dim_x')
    parser.add_argument('--output_dim_x', type=int, default=16, help='output_dim_x')
    parser.add_argument('--hidden_dim_a', type=int, default=128, help='hidden_dim_a')
    parser.add_argument('--output_dim_a', type=int, default=16, help='output_dim_a')
    parser.add_argument('--hidden_dim_g', type=int, default=128, help='hidden_dim_g')
    parser.add_argument('--output_dim_g', type=int, default=16, help='output_dim_g')
    parser.add_argument('--num_layers_x', type=int, default=2, help='num_layers_x')
    parser.add_argument('--num_layers_a', type=int, default=2, help='num_layers_a')
    parser.add_argument('--epoch', type=int, default=100000, help='')
    parser.add_argument('--patience', type=int, default=1000, help='')
    parser.add_argument('--lr', type=float, default=0.0005, help='')
    parser.add_argument('--weight_decay', type=float, default=0.0, help='')
    parser.add_argument('--update_interval', type=int, default=1, help='')
    parser.add_argument('--random_seed', type=int, default=2023, help='')
    args = parser.parse_args()
    return args

def texas(parser):
    parser.add_argument('--model_name', type=str, default='SMHGC_texas', help='model_name')
    parser.add_argument('--path', type=str, default='./data/', help='The path of datasets')
    parser.add_argument('--order', type=int, default=10, help='aggregation orders')
    parser.add_argument('--weight_soft_h', type=int, default=3, help='weight_soft_h')
    parser.add_argument('--weight_soft_S', type=int, default=3, help='weight_soft_S')
    parser.add_argument('--K', type=int, default=30, help='discretize with k')
    parser.add_argument('--hidden_dim_x', type=int, default=128, help='hidden_dim_x')
    parser.add_argument('--output_dim_x', type=int, default=32, help='output_dim_x')
    parser.add_argument('--hidden_dim_a', type=int, default=512, help='hidden_dim_a')
    parser.add_argument('--output_dim_a', type=int, default=128, help='output_dim_a')
    parser.add_argument('--hidden_dim_g', type=int, default=128, help='hidden_dim_g')
    parser.add_argument('--output_dim_g', type=int, default=32, help='output_dim_g')
    parser.add_argument('--num_layers_x', type=int, default=4, help='num_layers_x')
    parser.add_argument('--num_layers_a', type=int, default=4, help='num_layers_a')
    parser.add_argument('--epoch', type=int, default=100000, help='')
    parser.add_argument('--patience', type=int, default=1000, help='')
    parser.add_argument('--lr', type=float, default=1e-3, help='')
    parser.add_argument('--weight_decay', type=float, default=0.0001, help='')
    parser.add_argument('--update_interval', type=int, default=1, help='')
    parser.add_argument('--random_seed', type=int, default=2023, help='')
    args = parser.parse_args()
    return args

def chameleon(parser):
    parser.add_argument('--model_name', type=str, default='SMHGC_chameleon', help='model_name')
    parser.add_argument('--path', type=str, default='./data/', help='The path of datasets')
    parser.add_argument('--order', type=int, default=10, help='aggregation orders')
    parser.add_argument('--weight_soft_h', type=int, default=3, help='weight_soft_h')
    parser.add_argument('--weight_soft_S', type=int, default=3, help='weight_soft_S')
    parser.add_argument('--K', type=int, default=250, help='discretize with k')
    parser.add_argument('--hidden_dim_x', type=int, default=1024, help='hidden_dim_x')
    parser.add_argument('--output_dim_x', type=int, default=32, help='output_dim_x')
    parser.add_argument('--hidden_dim_a', type=int, default=1024, help='hidden_dim_a')
    parser.add_argument('--output_dim_a', type=int, default=32, help='output_dim_a')
    parser.add_argument('--hidden_dim_g', type=int, default=1024, help='hidden_dim_g')
    parser.add_argument('--output_dim_g', type=int, default=32, help='output_dim_g')
    parser.add_argument('--num_layers_x', type=int, default=4, help='num_layers_x')
    parser.add_argument('--num_layers_a', type=int, default=4, help='num_layers_a')
    parser.add_argument('--epoch', type=int, default=100000, help='')
    parser.add_argument('--patience', type=int, default=1000, help='')
    parser.add_argument('--lr', type=float, default=0.005, help='')
    parser.add_argument('--weight_decay', type=float, default=0.005, help='')
    parser.add_argument('--update_interval', type=int, default=1, help='')
    parser.add_argument('--random_seed', type=int, default=2023, help='')
    args = parser.parse_args()
    return args

def dblp(parser):
    parser.add_argument('--model_name', type=str, default='SMHGC_dblp', help='model_name')
    parser.add_argument('--path', type=str, default='./data/', help='The path of datasets')
    parser.add_argument('--order', type=int, default=6, help='aggregation orders')
    parser.add_argument('--weight_soft_h', type=int, default=3, help='weight_soft_h')
    parser.add_argument('--weight_soft_S', type=int, default=3, help='weight_soft_S')
    parser.add_argument('--K', type=int, default=300, help='discretize with k')
    parser.add_argument('--hidden_dim_x', type=int, default=128, help='hidden_dim_x')
    parser.add_argument('--output_dim_x', type=int, default=64, help='output_dim_x')
    parser.add_argument('--hidden_dim_a', type=int, default=256, help='hidden_dim_a')
    parser.add_argument('--output_dim_a', type=int, default=128, help='output_dim_a')
    parser.add_argument('--hidden_dim_g', type=int, default=128, help='hidden_dim_g')
    parser.add_argument('--output_dim_g', type=int, default=64, help='output_dim_g')
    parser.add_argument('--num_layers_x', type=int, default=2, help='num_layers_x')
    parser.add_argument('--num_layers_a', type=int, default=4, help='num_layers_a')
    parser.add_argument('--epoch', type=int, default=100000, help='')
    parser.add_argument('--patience', type=int, default=1000, help='')
    parser.add_argument('--lr', type=float, default=0.005, help='')
    parser.add_argument('--weight_decay', type=float, default=5e-7, help='')
    parser.add_argument('--update_interval', type=int, default=1, help='')
    parser.add_argument('--random_seed', type=int, default=2023, help='')
    args = parser.parse_args()
    return args

def acm00(parser):
    parser.add_argument('--model_name', type=str, default='SMHGC_acm00', help='model_name')
    parser.add_argument('--path', type=str, default='./data/', help='The path of datasets')
    parser.add_argument('--order', type=int, default=10, help='aggregation orders')
    parser.add_argument('--weight_soft_h', type=int, default=3, help='weight_soft_h')
    parser.add_argument('--weight_soft_S', type=int, default=3, help='weight_soft_S')
    parser.add_argument('--K', type=int, default=250, help='discretize with k')
    parser.add_argument('--hidden_dim_x', type=int, default=128, help='hidden_dim_x')
    parser.add_argument('--output_dim_x', type=int, default=32, help='output_dim_x')
    parser.add_argument('--hidden_dim_a', type=int, default=128, help='hidden_dim_a')
    parser.add_argument('--output_dim_a', type=int, default=32, help='output_dim_a')
    parser.add_argument('--hidden_dim_g', type=int, default=128, help='hidden_dim_g')
    parser.add_argument('--output_dim_g', type=int, default=32, help='output_dim_g')
    parser.add_argument('--num_layers_x', type=int, default=2, help='num_layers_x')
    parser.add_argument('--num_layers_a', type=int, default=4, help='num_layers_a')
    parser.add_argument('--epoch', type=int, default=100000, help='')
    parser.add_argument('--patience', type=int, default=1000, help='')
    parser.add_argument('--lr', type=float, default=0.001, help='')
    parser.add_argument('--weight_decay', type=float, default=0.005, help='')
    parser.add_argument('--update_interval', type=int, default=1, help='')
    parser.add_argument('--random_seed', type=int, default=2023, help='')
    args = parser.parse_args()
    return args

def acm01(parser):
    parser.add_argument('--model_name', type=str, default='SMHGC_acm01', help='model_name')
    parser.add_argument('--path', type=str, default='./data/', help='The path of datasets')
    parser.add_argument('--order', type=int, default=10, help='aggregation orders')
    parser.add_argument('--weight_soft_h', type=int, default=3, help='weight_soft_h')
    parser.add_argument('--weight_soft_S', type=int, default=3, help='weight_soft_S')
    parser.add_argument('--K', type=int, default=250, help='discretize with k')
    parser.add_argument('--hidden_dim_x', type=int, default=128, help='hidden_dim_x')
    parser.add_argument('--output_dim_x', type=int, default=32, help='output_dim_x')
    parser.add_argument('--hidden_dim_a', type=int, default=128, help='hidden_dim_a')
    parser.add_argument('--output_dim_a', type=int, default=32, help='output_dim_a')
    parser.add_argument('--hidden_dim_g', type=int, default=128, help='hidden_dim_g')
    parser.add_argument('--output_dim_g', type=int, default=32, help='output_dim_g')
    parser.add_argument('--num_layers_x', type=int, default=2, help='num_layers_x')
    parser.add_argument('--num_layers_a', type=int, default=4, help='num_layers_a')
    parser.add_argument('--epoch', type=int, default=100000, help='')
    parser.add_argument('--patience', type=int, default=1000, help='')
    parser.add_argument('--lr', type=float, default=0.001, help='')
    parser.add_argument('--weight_decay', type=float, default=0.005, help='')
    parser.add_argument('--update_interval', type=int, default=1, help='')
    parser.add_argument('--random_seed', type=int, default=2023, help='')
    args = parser.parse_args()
    return args

def acm02(parser):
    parser.add_argument('--model_name', type=str, default='SMHGC_acm02', help='model_name')
    parser.add_argument('--path', type=str, default='./data/', help='The path of datasets')
    parser.add_argument('--order', type=int, default=10, help='aggregation orders')
    parser.add_argument('--weight_soft_h', type=int, default=3, help='weight_soft_h')
    parser.add_argument('--weight_soft_S', type=int, default=3, help='weight_soft_S')
    parser.add_argument('--K', type=int, default=250, help='discretize with k')
    parser.add_argument('--hidden_dim_x', type=int, default=128, help='hidden_dim_x')
    parser.add_argument('--output_dim_x', type=int, default=32, help='output_dim_x')
    parser.add_argument('--hidden_dim_a', type=int, default=128, help='hidden_dim_a')
    parser.add_argument('--output_dim_a', type=int, default=32, help='output_dim_a')
    parser.add_argument('--hidden_dim_g', type=int, default=128, help='hidden_dim_g')
    parser.add_argument('--output_dim_g', type=int, default=32, help='output_dim_g')
    parser.add_argument('--num_layers_x', type=int, default=2, help='num_layers_x')
    parser.add_argument('--num_layers_a', type=int, default=4, help='num_layers_a')
    parser.add_argument('--epoch', type=int, default=100000, help='')
    parser.add_argument('--patience', type=int, default=1000, help='')
    parser.add_argument('--lr', type=float, default=0.005, help='')
    parser.add_argument('--weight_decay', type=float, default=5e-5, help='')
    parser.add_argument('--update_interval', type=int, default=1, help='')
    parser.add_argument('--random_seed', type=int, default=2023, help='')
    args = parser.parse_args()
    return args

def acm03(parser):
    parser.add_argument('--model_name', type=str, default='SMHGC_acm03', help='model_name')
    parser.add_argument('--path', type=str, default='./data/', help='The path of datasets')
    parser.add_argument('--order', type=int, default=10, help='aggregation orders')
    parser.add_argument('--weight_soft_h', type=int, default=3, help='weight_soft_h')
    parser.add_argument('--weight_soft_S', type=int, default=3, help='weight_soft_S')
    parser.add_argument('--K', type=int, default=250, help='discretize with k')
    parser.add_argument('--hidden_dim_x', type=int, default=512, help='hidden_dim_x')
    parser.add_argument('--output_dim_x', type=int, default=128, help='output_dim_x')
    parser.add_argument('--hidden_dim_a', type=int, default=512, help='hidden_dim_a')
    parser.add_argument('--output_dim_a', type=int, default=128, help='output_dim_a')
    parser.add_argument('--hidden_dim_g', type=int, default=512, help='hidden_dim_g')
    parser.add_argument('--output_dim_g', type=int, default=128, help='output_dim_g')
    parser.add_argument('--num_layers_x', type=int, default=2, help='num_layers_x')
    parser.add_argument('--num_layers_a', type=int, default=4, help='num_layers_a')
    parser.add_argument('--epoch', type=int, default=100000, help='')
    parser.add_argument('--patience', type=int, default=1000, help='')
    parser.add_argument('--lr', type=float, default=0.001, help='')
    parser.add_argument('--weight_decay', type=float, default=1e-5, help='')
    parser.add_argument('--update_interval', type=int, default=1, help='')
    parser.add_argument('--random_seed', type=int, default=2023, help='')
    args = parser.parse_args()
    return args

def acm04(parser):
    parser.add_argument('--model_name', type=str, default='SMHGC_acm04', help='model_name')
    parser.add_argument('--path', type=str, default='./data/', help='The path of datasets')
    parser.add_argument('--order', type=int, default=7, help='aggregation orders')
    parser.add_argument('--weight_soft_h', type=int, default=3, help='weight_soft_h')
    parser.add_argument('--weight_soft_S', type=int, default=3, help='weight_soft_S')
    parser.add_argument('--K', type=int, default=250, help='discretize with k')
    parser.add_argument('--hidden_dim_x', type=int, default=512, help='hidden_dim_x')
    parser.add_argument('--output_dim_x', type=int, default=256, help='output_dim_x')
    parser.add_argument('--hidden_dim_a', type=int, default=512, help='hidden_dim_a')
    parser.add_argument('--output_dim_a', type=int, default=256, help='output_dim_a')
    parser.add_argument('--hidden_dim_g', type=int, default=512, help='hidden_dim_g')
    parser.add_argument('--output_dim_g', type=int, default=256, help='output_dim_g')
    parser.add_argument('--num_layers_x', type=int, default=2, help='num_layers_x')
    parser.add_argument('--num_layers_a', type=int, default=4, help='num_layers_a')
    parser.add_argument('--epoch', type=int, default=100000, help='')
    parser.add_argument('--patience', type=int, default=1000, help='')
    parser.add_argument('--lr', type=float, default=0.001, help='')
    parser.add_argument('--weight_decay', type=float, default=0.0, help='')
    parser.add_argument('--update_interval', type=int, default=1, help='')
    parser.add_argument('--random_seed', type=int, default=2023, help='')
    args = parser.parse_args()
    return args

def acm05(parser):
    parser.add_argument('--model_name', type=str, default='SMHGC_acm05', help='model_name')
    parser.add_argument('--path', type=str, default='./data/', help='The path of datasets')
    parser.add_argument('--order', type=int, default=10, help='aggregation orders')
    parser.add_argument('--weight_soft_h', type=int, default=3, help='weight_soft_h')
    parser.add_argument('--weight_soft_S', type=int, default=3, help='weight_soft_S')
    parser.add_argument('--K', type=int, default=250, help='discretize with k')
    parser.add_argument('--hidden_dim_x', type=int, default=128, help='hidden_dim_x')
    parser.add_argument('--output_dim_x', type=int, default=32, help='output_dim_x')
    parser.add_argument('--hidden_dim_a', type=int, default=128, help='hidden_dim_a')
    parser.add_argument('--output_dim_a', type=int, default=32, help='output_dim_a')
    parser.add_argument('--hidden_dim_g', type=int, default=128, help='hidden_dim_g')
    parser.add_argument('--output_dim_g', type=int, default=32, help='output_dim_g')
    parser.add_argument('--num_layers_x', type=int, default=2, help='num_layers_x')
    parser.add_argument('--num_layers_a', type=int, default=4, help='num_layers_a')
    parser.add_argument('--epoch', type=int, default=100000, help='')
    parser.add_argument('--patience', type=int, default=1000, help='')
    parser.add_argument('--lr', type=float, default=0.005, help='')
    parser.add_argument('--weight_decay', type=float, default=0.005, help='')
    parser.add_argument('--update_interval', type=int, default=10, help='')
    parser.add_argument('--random_seed', type=int, default=2023, help='')
    args = parser.parse_args()
    return args


def get_settings(parser, dataset='acm'):
    args_dic = {
        'acm': acm,
        'dblp': dblp,
        'texas': texas,
        'chameleon': chameleon,
        'acm00': acm00,
        'acm01': acm01,
        'acm02': acm02,
        'acm03': acm03,
        'acm04': acm04,
        'acm05': acm05,
    }
    return args_dic[dataset](parser)
